spring.application.name=orbitron
spring.datasource.url=jdbc:postgresql://localhost:5432/airports
spring.datasource.username=postgres
spring.datasource.password=41852001
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
logging.level.root=WARN
logging.level.com.example.orbitron=DEBUG


